{% set version = "7.6.3" %}

package:
  name: coverage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coverage/coverage-{{ version }}.tar.gz
  sha256: bb7d5fe92bd0dc235f63ebe9f8c6e0884f7360f88f3411bfed1350c872ef2054

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    # extra dependency
    - tomli

test:
  requires:
    - pip
  imports:
    - coverage
  commands:
    - pip check
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python

extra:
  recipe-maintainers:
    - thewchan
    - ericmjl
    - jakirkham
    - ocefpaf
