{% set version = "7.6.6" %}

package:
  name: coverage
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/coverage/coverage-{{ version }}.tar.gz
  sha256: 84f91414af6cfa55821eb96b8e43bc1955774f57fe04af8bcaf8769123eddf4d

build:
  number: 0
  noarch: python  # [use_noarch]
  track_features:
    - coverage_no_compile                 # [use_noarch]
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - python                                 # [build_platform != target_platform and not use_noarch]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python         # [not use_noarch]
    - python {{ python_min }}   # [use_noarch]
    - pip
    - setuptools
  run:
    - python         # [not use_noarch]
    - python >={{ python_min }}   # [use_noarch]
    # extra dependency
    - tomli

test:
  requires:
    - pip
    - python {{ python_min }}  # [use_noarch]
  imports:
    - coverage
  commands:
    - pip check
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python

extra:
  recipe-maintainers:
    - thewchan
    - ericmjl
    - jakirkham
    - ocefpaf
